{{- if .Values.env.openaiApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "medspa-bot.fullname" . }}
  labels:
    {{- include "medspa-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENAI_API_KEY: "{{ .Values.env.openaiApiKey }}"
{{- end }}
